/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthTabsImport } from './routes/_auth/tabs'
import { Route as AuthShopsImport } from './routes/_auth/shops'
import { Route as AuthProfileImport } from './routes/_auth/profile'
import { Route as AuthShopsIndexImport } from './routes/_auth/shops/index'
import { Route as AuthShopsShopIdImport } from './routes/_auth/shops/$shopId'
import { Route as AuthShopsShopIdTabRequestImport } from './routes/_auth/shops/$shopId/tab-request'
import { Route as AuthShopsShopIdShopuserImport } from './routes/_auth/shops/$shopId/_shopuser'
import { Route as AuthShopsShopIdShopuserTabsImport } from './routes/_auth/shops/$shopId/_shopuser/tabs'
import { Route as AuthShopsShopIdShopuserItemsImport } from './routes/_auth/shops/$shopId/_shopuser/items'
import { Route as AuthShopsShopIdShopuserCheckoutImport } from './routes/_auth/shops/$shopId/_shopuser/checkout'
import { Route as AuthShopsShopIdShopuserLayoutImport } from './routes/_auth/shops/$shopId/_shopuser/_layout'
import { Route as AuthShopsShopIdShopuserItemsIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/index'
import { Route as AuthShopsShopIdShopuserLayoutIndexImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/index'
import { Route as AuthShopsShopIdShopuserTabsTabIdImport } from './routes/_auth/shops/$shopId/_shopuser/tabs/$tabId'
import { Route as AuthShopsShopIdShopuserItemsItemIdImport } from './routes/_auth/shops/$shopId/_shopuser/items/$itemId'
import { Route as AuthShopsShopIdShopuserCheckoutItemIdImport } from './routes/_auth/shops/$shopId/_shopuser/checkout/$itemId'
import { Route as AuthShopsShopIdShopuserLayoutUsersImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/users'
import { Route as AuthShopsShopIdShopuserLayoutLocationsImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/locations'
import { Route as AuthShopsShopIdShopuserLayoutIntegrationsImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/integrations'
import { Route as AuthShopsShopIdShopuserTabsTabIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/tabs/$tabId.index'
import { Route as AuthShopsShopIdShopuserItemsItemIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/$itemId.index'
import { Route as AuthShopsShopIdShopuserCheckoutItemIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/checkout/$itemId.index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthTabsRoute = AuthTabsImport.update({
  path: '/tabs',
  getParentRoute: () => AuthRoute,
} as any)

const AuthShopsRoute = AuthShopsImport.update({
  path: '/shops',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthShopsIndexRoute = AuthShopsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthShopsRoute,
} as any)

const AuthShopsShopIdRoute = AuthShopsShopIdImport.update({
  path: '/$shopId',
  getParentRoute: () => AuthShopsRoute,
} as any)

const AuthShopsShopIdTabRequestRoute = AuthShopsShopIdTabRequestImport.update({
  path: '/tab-request',
  getParentRoute: () => AuthShopsShopIdRoute,
} as any)

const AuthShopsShopIdShopuserRoute = AuthShopsShopIdShopuserImport.update({
  id: '/_shopuser',
  getParentRoute: () => AuthShopsShopIdRoute,
} as any)

const AuthShopsShopIdShopuserTabsRoute =
  AuthShopsShopIdShopuserTabsImport.update({
    path: '/tabs',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserItemsRoute =
  AuthShopsShopIdShopuserItemsImport.update({
    path: '/items',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutRoute =
  AuthShopsShopIdShopuserCheckoutImport.update({
    path: '/checkout',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutRoute =
  AuthShopsShopIdShopuserLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserItemsIndexRoute =
  AuthShopsShopIdShopuserItemsIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutIndexRoute =
  AuthShopsShopIdShopuserLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserTabsTabIdRoute =
  AuthShopsShopIdShopuserTabsTabIdImport.update({
    path: '/$tabId',
    getParentRoute: () => AuthShopsShopIdShopuserTabsRoute,
  } as any)

const AuthShopsShopIdShopuserItemsItemIdRoute =
  AuthShopsShopIdShopuserItemsItemIdImport.update({
    path: '/$itemId',
    getParentRoute: () => AuthShopsShopIdShopuserItemsRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutItemIdRoute =
  AuthShopsShopIdShopuserCheckoutItemIdImport.update({
    path: '/$itemId',
    getParentRoute: () => AuthShopsShopIdShopuserCheckoutRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutUsersRoute =
  AuthShopsShopIdShopuserLayoutUsersImport.update({
    path: '/users',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutLocationsRoute =
  AuthShopsShopIdShopuserLayoutLocationsImport.update({
    path: '/locations',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutIntegrationsRoute =
  AuthShopsShopIdShopuserLayoutIntegrationsImport.update({
    path: '/integrations',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserTabsTabIdIndexRoute =
  AuthShopsShopIdShopuserTabsTabIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserTabsTabIdRoute,
  } as any)

const AuthShopsShopIdShopuserItemsItemIdIndexRoute =
  AuthShopsShopIdShopuserItemsItemIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsItemIdRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutItemIdIndexRoute =
  AuthShopsShopIdShopuserCheckoutItemIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserCheckoutItemIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/shops': {
      id: '/_auth/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AuthShopsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/tabs': {
      id: '/_auth/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof AuthTabsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/shops/$shopId': {
      id: '/_auth/shops/$shopId'
      path: '/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdImport
      parentRoute: typeof AuthShopsImport
    }
    '/_auth/shops/': {
      id: '/_auth/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof AuthShopsIndexImport
      parentRoute: typeof AuthShopsImport
    }
    '/_auth/shops/$shopId/_shopuser': {
      id: '/_auth/shops/$shopId/_shopuser'
      path: ''
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserImport
      parentRoute: typeof AuthShopsShopIdImport
    }
    '/_auth/shops/$shopId/tab-request': {
      id: '/_auth/shops/$shopId/tab-request'
      path: '/tab-request'
      fullPath: '/shops/$shopId/tab-request'
      preLoaderRoute: typeof AuthShopsShopIdTabRequestImport
      parentRoute: typeof AuthShopsShopIdImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout': {
      id: '/_auth/shops/$shopId/_shopuser/_layout'
      path: ''
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout': {
      id: '/_auth/shops/$shopId/_shopuser/checkout'
      path: '/checkout'
      fullPath: '/shops/$shopId/checkout'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/items': {
      id: '/_auth/shops/$shopId/_shopuser/items'
      path: '/items'
      fullPath: '/shops/$shopId/items'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs': {
      id: '/_auth/shops/$shopId/_shopuser/tabs'
      path: '/tabs'
      fullPath: '/shops/$shopId/tabs'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/integrations': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/integrations'
      path: '/integrations'
      fullPath: '/shops/$shopId/integrations'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutIntegrationsImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/locations': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/locations'
      path: '/locations'
      fullPath: '/shops/$shopId/locations'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutLocationsImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/users': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/users'
      path: '/users'
      fullPath: '/shops/$shopId/users'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutUsersImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout/$itemId': {
      id: '/_auth/shops/$shopId/_shopuser/checkout/$itemId'
      path: '/$itemId'
      fullPath: '/shops/$shopId/checkout/$itemId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdImport
      parentRoute: typeof AuthShopsShopIdShopuserCheckoutImport
    }
    '/_auth/shops/$shopId/_shopuser/items/$itemId': {
      id: '/_auth/shops/$shopId/_shopuser/items/$itemId'
      path: '/$itemId'
      fullPath: '/shops/$shopId/items/$itemId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsItemIdImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs/$tabId': {
      id: '/_auth/shops/$shopId/_shopuser/tabs/$tabId'
      path: '/$tabId'
      fullPath: '/shops/$shopId/tabs/$tabId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsTabIdImport
      parentRoute: typeof AuthShopsShopIdShopuserTabsImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/'
      path: '/'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/items/': {
      id: '/_auth/shops/$shopId/_shopuser/items/'
      path: '/'
      fullPath: '/shops/$shopId/items/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout/$itemId/': {
      id: '/_auth/shops/$shopId/_shopuser/checkout/$itemId/'
      path: '/'
      fullPath: '/shops/$shopId/checkout/$itemId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdImport
    }
    '/_auth/shops/$shopId/_shopuser/items/$itemId/': {
      id: '/_auth/shops/$shopId/_shopuser/items/$itemId/'
      path: '/'
      fullPath: '/shops/$shopId/items/$itemId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsItemIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsItemIdImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs/$tabId/': {
      id: '/_auth/shops/$shopId/_shopuser/tabs/$tabId/'
      path: '/'
      fullPath: '/shops/$shopId/tabs/$tabId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsTabIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserTabsTabIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthProfileRoute,
    AuthShopsRoute: AuthShopsRoute.addChildren({
      AuthShopsShopIdRoute: AuthShopsShopIdRoute.addChildren({
        AuthShopsShopIdShopuserRoute: AuthShopsShopIdShopuserRoute.addChildren({
          AuthShopsShopIdShopuserLayoutRoute:
            AuthShopsShopIdShopuserLayoutRoute.addChildren({
              AuthShopsShopIdShopuserLayoutIntegrationsRoute,
              AuthShopsShopIdShopuserLayoutLocationsRoute,
              AuthShopsShopIdShopuserLayoutUsersRoute,
              AuthShopsShopIdShopuserLayoutIndexRoute,
            }),
          AuthShopsShopIdShopuserCheckoutRoute:
            AuthShopsShopIdShopuserCheckoutRoute.addChildren({
              AuthShopsShopIdShopuserCheckoutItemIdRoute:
                AuthShopsShopIdShopuserCheckoutItemIdRoute.addChildren({
                  AuthShopsShopIdShopuserCheckoutItemIdIndexRoute,
                }),
            }),
          AuthShopsShopIdShopuserItemsRoute:
            AuthShopsShopIdShopuserItemsRoute.addChildren({
              AuthShopsShopIdShopuserItemsItemIdRoute:
                AuthShopsShopIdShopuserItemsItemIdRoute.addChildren({
                  AuthShopsShopIdShopuserItemsItemIdIndexRoute,
                }),
              AuthShopsShopIdShopuserItemsIndexRoute,
            }),
          AuthShopsShopIdShopuserTabsRoute:
            AuthShopsShopIdShopuserTabsRoute.addChildren({
              AuthShopsShopIdShopuserTabsTabIdRoute:
                AuthShopsShopIdShopuserTabsTabIdRoute.addChildren({
                  AuthShopsShopIdShopuserTabsTabIdIndexRoute,
                }),
            }),
        }),
        AuthShopsShopIdTabRequestRoute,
      }),
      AuthShopsIndexRoute,
    }),
    AuthTabsRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/profile",
        "/_auth/shops",
        "/_auth/tabs"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/profile": {
      "filePath": "_auth/profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/shops": {
      "filePath": "_auth/shops.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/shops/$shopId",
        "/_auth/shops/"
      ]
    },
    "/_auth/tabs": {
      "filePath": "_auth/tabs.tsx",
      "parent": "/_auth"
    },
    "/_auth/shops/$shopId": {
      "filePath": "_auth/shops/$shopId.tsx",
      "parent": "/_auth/shops",
      "children": [
        "/_auth/shops/$shopId/_shopuser",
        "/_auth/shops/$shopId/tab-request"
      ]
    },
    "/_auth/shops/": {
      "filePath": "_auth/shops/index.tsx",
      "parent": "/_auth/shops"
    },
    "/_auth/shops/$shopId/_shopuser": {
      "filePath": "_auth/shops/$shopId/_shopuser.tsx",
      "parent": "/_auth/shops/$shopId",
      "children": [
        "/_auth/shops/$shopId/_shopuser/_layout",
        "/_auth/shops/$shopId/_shopuser/checkout",
        "/_auth/shops/$shopId/_shopuser/items",
        "/_auth/shops/$shopId/_shopuser/tabs"
      ]
    },
    "/_auth/shops/$shopId/tab-request": {
      "filePath": "_auth/shops/$shopId/tab-request.tsx",
      "parent": "/_auth/shops/$shopId"
    },
    "/_auth/shops/$shopId/_shopuser/_layout": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/_layout/integrations",
        "/_auth/shops/$shopId/_shopuser/_layout/locations",
        "/_auth/shops/$shopId/_shopuser/_layout/users",
        "/_auth/shops/$shopId/_shopuser/_layout/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/checkout": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/checkout/$itemId"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/items": {
      "filePath": "_auth/shops/$shopId/_shopuser/items.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/items/$itemId",
        "/_auth/shops/$shopId/_shopuser/items/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/tabs": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/tabs/$tabId"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/_layout/integrations": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/integrations.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/_layout/locations": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/locations.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/_layout/users": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/users.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/checkout/$itemId": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout/$itemId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/checkout",
      "children": [
        "/_auth/shops/$shopId/_shopuser/checkout/$itemId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/items/$itemId": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/$itemId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items",
      "children": [
        "/_auth/shops/$shopId/_shopuser/items/$itemId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/tabs/$tabId": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs/$tabId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/tabs",
      "children": [
        "/_auth/shops/$shopId/_shopuser/tabs/$tabId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/_layout/": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/items/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items"
    },
    "/_auth/shops/$shopId/_shopuser/checkout/$itemId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout/$itemId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/checkout/$itemId"
    },
    "/_auth/shops/$shopId/_shopuser/items/$itemId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/$itemId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items/$itemId"
    },
    "/_auth/shops/$shopId/_shopuser/tabs/$tabId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs/$tabId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/tabs/$tabId"
    }
  }
}
ROUTE_MANIFEST_END */
