/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashLayoutImport } from './routes/_dashLayout'
import { Route as AuthImport } from './routes/_auth'
import { Route as DashLayoutIndexImport } from './routes/_dashLayout.index'
import { Route as AuthDashImport } from './routes/_auth/_dash'
import { Route as AuthShopsShopIdImport } from './routes/_auth/shops/$shopId'
import { Route as AuthDashTabsImport } from './routes/_auth/_dash.tabs'
import { Route as AuthDashShopsImport } from './routes/_auth/_dash.shops'
import { Route as AuthDashProfileImport } from './routes/_auth/_dash.profile'
import { Route as AuthDashDashImport } from './routes/_auth/_dash.dash'
import { Route as AuthDashShopsIndexImport } from './routes/_auth/_dash.shops.index'
import { Route as AuthShopsShopIdTabRequestImport } from './routes/_auth/shops/$shopId/tab-request'
import { Route as AuthShopsShopIdShopuserImport } from './routes/_auth/shops/$shopId/_shopuser'
import { Route as AuthShopsShopIdShopuserTabsImport } from './routes/_auth/shops/$shopId/_shopuser/tabs'
import { Route as AuthShopsShopIdShopuserItemsImport } from './routes/_auth/shops/$shopId/_shopuser/items'
import { Route as AuthShopsShopIdShopuserCheckoutImport } from './routes/_auth/shops/$shopId/_shopuser/checkout'
import { Route as AuthShopsShopIdShopuserLayoutImport } from './routes/_auth/shops/$shopId/_shopuser/_layout'
import { Route as AuthShopsShopIdShopuserLayoutIndexImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/index'
import { Route as AuthShopsShopIdShopuserTabsTabIdImport } from './routes/_auth/shops/$shopId/_shopuser/tabs/$tabId'
import { Route as AuthShopsShopIdShopuserItemsIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/_index'
import { Route as AuthShopsShopIdShopuserCheckoutItemIdImport } from './routes/_auth/shops/$shopId/_shopuser/checkout/$itemId'
import { Route as AuthShopsShopIdShopuserLayoutUsersImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/users'
import { Route as AuthShopsShopIdShopuserLayoutIntegrationsImport } from './routes/_auth/shops/$shopId/_shopuser/_layout/integrations'
import { Route as AuthShopsShopIdShopuserTabsTabIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/tabs/$tabId.index'
import { Route as AuthShopsShopIdShopuserItemsSubstitutionsIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/substitutions.index'
import { Route as AuthShopsShopIdShopuserItemsCategoriesIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/categories.index'
import { Route as AuthShopsShopIdShopuserItemsIndexIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/_index.index'
import { Route as AuthShopsShopIdShopuserCheckoutItemIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/checkout/$itemId.index'
import { Route as AuthShopsShopIdShopuserItemsIndexItemIdImport } from './routes/_auth/shops/$shopId/_shopuser/items/_index.$itemId'
import { Route as AuthShopsShopIdShopuserItemsIndexItemIdIndexImport } from './routes/_auth/shops/$shopId/_shopuser/items/_index.$itemId.index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashLayoutRoute = DashLayoutImport.update({
  id: '/_dashLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const DashLayoutIndexRoute = DashLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashLayoutRoute,
} as any)

const AuthDashRoute = AuthDashImport.update({
  id: '/_dash',
  getParentRoute: () => AuthRoute,
} as any)

const AuthShopsShopIdRoute = AuthShopsShopIdImport.update({
  path: '/shops/$shopId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashTabsRoute = AuthDashTabsImport.update({
  path: '/tabs',
  getParentRoute: () => AuthDashRoute,
} as any)

const AuthDashShopsRoute = AuthDashShopsImport.update({
  path: '/shops',
  getParentRoute: () => AuthDashRoute,
} as any)

const AuthDashProfileRoute = AuthDashProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthDashRoute,
} as any)

const AuthDashDashRoute = AuthDashDashImport.update({
  path: '/dash',
  getParentRoute: () => AuthDashRoute,
} as any)

const AuthDashShopsIndexRoute = AuthDashShopsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthDashShopsRoute,
} as any)

const AuthShopsShopIdTabRequestRoute = AuthShopsShopIdTabRequestImport.update({
  path: '/tab-request',
  getParentRoute: () => AuthShopsShopIdRoute,
} as any)

const AuthShopsShopIdShopuserRoute = AuthShopsShopIdShopuserImport.update({
  id: '/_shopuser',
  getParentRoute: () => AuthShopsShopIdRoute,
} as any)

const AuthShopsShopIdShopuserTabsRoute =
  AuthShopsShopIdShopuserTabsImport.update({
    path: '/tabs',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserItemsRoute =
  AuthShopsShopIdShopuserItemsImport.update({
    path: '/items',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutRoute =
  AuthShopsShopIdShopuserCheckoutImport.update({
    path: '/checkout',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutRoute =
  AuthShopsShopIdShopuserLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthShopsShopIdShopuserRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutIndexRoute =
  AuthShopsShopIdShopuserLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserTabsTabIdRoute =
  AuthShopsShopIdShopuserTabsTabIdImport.update({
    path: '/$tabId',
    getParentRoute: () => AuthShopsShopIdShopuserTabsRoute,
  } as any)

const AuthShopsShopIdShopuserItemsIndexRoute =
  AuthShopsShopIdShopuserItemsIndexImport.update({
    id: '/_index',
    getParentRoute: () => AuthShopsShopIdShopuserItemsRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutItemIdRoute =
  AuthShopsShopIdShopuserCheckoutItemIdImport.update({
    path: '/$itemId',
    getParentRoute: () => AuthShopsShopIdShopuserCheckoutRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutUsersRoute =
  AuthShopsShopIdShopuserLayoutUsersImport.update({
    path: '/users',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserLayoutIntegrationsRoute =
  AuthShopsShopIdShopuserLayoutIntegrationsImport.update({
    path: '/integrations',
    getParentRoute: () => AuthShopsShopIdShopuserLayoutRoute,
  } as any)

const AuthShopsShopIdShopuserTabsTabIdIndexRoute =
  AuthShopsShopIdShopuserTabsTabIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserTabsTabIdRoute,
  } as any)

const AuthShopsShopIdShopuserItemsSubstitutionsIndexRoute =
  AuthShopsShopIdShopuserItemsSubstitutionsIndexImport.update({
    path: '/substitutions/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsRoute,
  } as any)

const AuthShopsShopIdShopuserItemsCategoriesIndexRoute =
  AuthShopsShopIdShopuserItemsCategoriesIndexImport.update({
    path: '/categories/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsRoute,
  } as any)

const AuthShopsShopIdShopuserItemsIndexIndexRoute =
  AuthShopsShopIdShopuserItemsIndexIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsIndexRoute,
  } as any)

const AuthShopsShopIdShopuserCheckoutItemIdIndexRoute =
  AuthShopsShopIdShopuserCheckoutItemIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserCheckoutItemIdRoute,
  } as any)

const AuthShopsShopIdShopuserItemsIndexItemIdRoute =
  AuthShopsShopIdShopuserItemsIndexItemIdImport.update({
    path: '/$itemId',
    getParentRoute: () => AuthShopsShopIdShopuserItemsIndexRoute,
  } as any)

const AuthShopsShopIdShopuserItemsIndexItemIdIndexRoute =
  AuthShopsShopIdShopuserItemsIndexItemIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthShopsShopIdShopuserItemsIndexItemIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashLayout': {
      id: '/_dashLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_dash': {
      id: '/_auth/_dash'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthDashImport
      parentRoute: typeof AuthImport
    }
    '/_dashLayout/': {
      id: '/_dashLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashLayoutIndexImport
      parentRoute: typeof DashLayoutImport
    }
    '/_auth/_dash/dash': {
      id: '/_auth/_dash/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof AuthDashDashImport
      parentRoute: typeof AuthDashImport
    }
    '/_auth/_dash/profile': {
      id: '/_auth/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthDashProfileImport
      parentRoute: typeof AuthDashImport
    }
    '/_auth/_dash/shops': {
      id: '/_auth/_dash/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AuthDashShopsImport
      parentRoute: typeof AuthDashImport
    }
    '/_auth/_dash/tabs': {
      id: '/_auth/_dash/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof AuthDashTabsImport
      parentRoute: typeof AuthDashImport
    }
    '/_auth/shops/$shopId': {
      id: '/_auth/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/shops/$shopId/_shopuser': {
      id: '/_auth/shops/$shopId/_shopuser'
      path: ''
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserImport
      parentRoute: typeof AuthShopsShopIdImport
    }
    '/_auth/shops/$shopId/tab-request': {
      id: '/_auth/shops/$shopId/tab-request'
      path: '/tab-request'
      fullPath: '/shops/$shopId/tab-request'
      preLoaderRoute: typeof AuthShopsShopIdTabRequestImport
      parentRoute: typeof AuthShopsShopIdImport
    }
    '/_auth/_dash/shops/': {
      id: '/_auth/_dash/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof AuthDashShopsIndexImport
      parentRoute: typeof AuthDashShopsImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout': {
      id: '/_auth/shops/$shopId/_shopuser/_layout'
      path: ''
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout': {
      id: '/_auth/shops/$shopId/_shopuser/checkout'
      path: '/checkout'
      fullPath: '/shops/$shopId/checkout'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/items': {
      id: '/_auth/shops/$shopId/_shopuser/items'
      path: '/items'
      fullPath: '/shops/$shopId/items'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs': {
      id: '/_auth/shops/$shopId/_shopuser/tabs'
      path: '/tabs'
      fullPath: '/shops/$shopId/tabs'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsImport
      parentRoute: typeof AuthShopsShopIdShopuserImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/integrations': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/integrations'
      path: '/integrations'
      fullPath: '/shops/$shopId/integrations'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutIntegrationsImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/users': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/users'
      path: '/users'
      fullPath: '/shops/$shopId/users'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutUsersImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout/$itemId': {
      id: '/_auth/shops/$shopId/_shopuser/checkout/$itemId'
      path: '/$itemId'
      fullPath: '/shops/$shopId/checkout/$itemId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdImport
      parentRoute: typeof AuthShopsShopIdShopuserCheckoutImport
    }
    '/_auth/shops/$shopId/_shopuser/items/_index': {
      id: '/_auth/shops/$shopId/_shopuser/items/_index'
      path: ''
      fullPath: '/shops/$shopId/items'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs/$tabId': {
      id: '/_auth/shops/$shopId/_shopuser/tabs/$tabId'
      path: '/$tabId'
      fullPath: '/shops/$shopId/tabs/$tabId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsTabIdImport
      parentRoute: typeof AuthShopsShopIdShopuserTabsImport
    }
    '/_auth/shops/$shopId/_shopuser/_layout/': {
      id: '/_auth/shops/$shopId/_shopuser/_layout/'
      path: '/'
      fullPath: '/shops/$shopId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserLayoutIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserLayoutImport
    }
    '/_auth/shops/$shopId/_shopuser/items/_index/$itemId': {
      id: '/_auth/shops/$shopId/_shopuser/items/_index/$itemId'
      path: '/$itemId'
      fullPath: '/shops/$shopId/items/$itemId'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsIndexItemIdImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsIndexImport
    }
    '/_auth/shops/$shopId/_shopuser/checkout/$itemId/': {
      id: '/_auth/shops/$shopId/_shopuser/checkout/$itemId/'
      path: '/'
      fullPath: '/shops/$shopId/checkout/$itemId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserCheckoutItemIdImport
    }
    '/_auth/shops/$shopId/_shopuser/items/_index/': {
      id: '/_auth/shops/$shopId/_shopuser/items/_index/'
      path: '/'
      fullPath: '/shops/$shopId/items/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsIndexIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsIndexImport
    }
    '/_auth/shops/$shopId/_shopuser/items/categories/': {
      id: '/_auth/shops/$shopId/_shopuser/items/categories/'
      path: '/categories'
      fullPath: '/shops/$shopId/items/categories'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsCategoriesIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsImport
    }
    '/_auth/shops/$shopId/_shopuser/items/substitutions/': {
      id: '/_auth/shops/$shopId/_shopuser/items/substitutions/'
      path: '/substitutions'
      fullPath: '/shops/$shopId/items/substitutions'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsSubstitutionsIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsImport
    }
    '/_auth/shops/$shopId/_shopuser/tabs/$tabId/': {
      id: '/_auth/shops/$shopId/_shopuser/tabs/$tabId/'
      path: '/'
      fullPath: '/shops/$shopId/tabs/$tabId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserTabsTabIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserTabsTabIdImport
    }
    '/_auth/shops/$shopId/_shopuser/items/_index/$itemId/': {
      id: '/_auth/shops/$shopId/_shopuser/items/_index/$itemId/'
      path: '/'
      fullPath: '/shops/$shopId/items/$itemId/'
      preLoaderRoute: typeof AuthShopsShopIdShopuserItemsIndexItemIdIndexImport
      parentRoute: typeof AuthShopsShopIdShopuserItemsIndexItemIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthDashRoute: AuthDashRoute.addChildren({
      AuthDashDashRoute,
      AuthDashProfileRoute,
      AuthDashShopsRoute: AuthDashShopsRoute.addChildren({
        AuthDashShopsIndexRoute,
      }),
      AuthDashTabsRoute,
    }),
    AuthShopsShopIdRoute: AuthShopsShopIdRoute.addChildren({
      AuthShopsShopIdShopuserRoute: AuthShopsShopIdShopuserRoute.addChildren({
        AuthShopsShopIdShopuserLayoutRoute:
          AuthShopsShopIdShopuserLayoutRoute.addChildren({
            AuthShopsShopIdShopuserLayoutIntegrationsRoute,
            AuthShopsShopIdShopuserLayoutUsersRoute,
            AuthShopsShopIdShopuserLayoutIndexRoute,
          }),
        AuthShopsShopIdShopuserCheckoutRoute:
          AuthShopsShopIdShopuserCheckoutRoute.addChildren({
            AuthShopsShopIdShopuserCheckoutItemIdRoute:
              AuthShopsShopIdShopuserCheckoutItemIdRoute.addChildren({
                AuthShopsShopIdShopuserCheckoutItemIdIndexRoute,
              }),
          }),
        AuthShopsShopIdShopuserItemsRoute:
          AuthShopsShopIdShopuserItemsRoute.addChildren({
            AuthShopsShopIdShopuserItemsIndexRoute:
              AuthShopsShopIdShopuserItemsIndexRoute.addChildren({
                AuthShopsShopIdShopuserItemsIndexItemIdRoute:
                  AuthShopsShopIdShopuserItemsIndexItemIdRoute.addChildren({
                    AuthShopsShopIdShopuserItemsIndexItemIdIndexRoute,
                  }),
                AuthShopsShopIdShopuserItemsIndexIndexRoute,
              }),
            AuthShopsShopIdShopuserItemsCategoriesIndexRoute,
            AuthShopsShopIdShopuserItemsSubstitutionsIndexRoute,
          }),
        AuthShopsShopIdShopuserTabsRoute:
          AuthShopsShopIdShopuserTabsRoute.addChildren({
            AuthShopsShopIdShopuserTabsTabIdRoute:
              AuthShopsShopIdShopuserTabsTabIdRoute.addChildren({
                AuthShopsShopIdShopuserTabsTabIdIndexRoute,
              }),
          }),
      }),
      AuthShopsShopIdTabRequestRoute,
    }),
  }),
  DashLayoutRoute: DashLayoutRoute.addChildren({ DashLayoutIndexRoute }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_dashLayout",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_dash",
        "/_auth/shops/$shopId"
      ]
    },
    "/_dashLayout": {
      "filePath": "_dashLayout.tsx",
      "children": [
        "/_dashLayout/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/_dash": {
      "filePath": "_auth/_dash.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_dash/dash",
        "/_auth/_dash/profile",
        "/_auth/_dash/shops",
        "/_auth/_dash/tabs"
      ]
    },
    "/_dashLayout/": {
      "filePath": "_dashLayout.index.tsx",
      "parent": "/_dashLayout"
    },
    "/_auth/_dash/dash": {
      "filePath": "_auth/_dash.dash.tsx",
      "parent": "/_auth/_dash"
    },
    "/_auth/_dash/profile": {
      "filePath": "_auth/_dash.profile.tsx",
      "parent": "/_auth/_dash"
    },
    "/_auth/_dash/shops": {
      "filePath": "_auth/_dash.shops.tsx",
      "parent": "/_auth/_dash",
      "children": [
        "/_auth/_dash/shops/"
      ]
    },
    "/_auth/_dash/tabs": {
      "filePath": "_auth/_dash.tabs.tsx",
      "parent": "/_auth/_dash"
    },
    "/_auth/shops/$shopId": {
      "filePath": "_auth/shops/$shopId.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/shops/$shopId/_shopuser",
        "/_auth/shops/$shopId/tab-request"
      ]
    },
    "/_auth/shops/$shopId/_shopuser": {
      "filePath": "_auth/shops/$shopId/_shopuser.tsx",
      "parent": "/_auth/shops/$shopId",
      "children": [
        "/_auth/shops/$shopId/_shopuser/_layout",
        "/_auth/shops/$shopId/_shopuser/checkout",
        "/_auth/shops/$shopId/_shopuser/items",
        "/_auth/shops/$shopId/_shopuser/tabs"
      ]
    },
    "/_auth/shops/$shopId/tab-request": {
      "filePath": "_auth/shops/$shopId/tab-request.tsx",
      "parent": "/_auth/shops/$shopId"
    },
    "/_auth/_dash/shops/": {
      "filePath": "_auth/_dash.shops.index.tsx",
      "parent": "/_auth/_dash/shops"
    },
    "/_auth/shops/$shopId/_shopuser/_layout": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/_layout/integrations",
        "/_auth/shops/$shopId/_shopuser/_layout/users",
        "/_auth/shops/$shopId/_shopuser/_layout/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/checkout": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/checkout/$itemId"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/items": {
      "filePath": "_auth/shops/$shopId/_shopuser/items.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/items/_index",
        "/_auth/shops/$shopId/_shopuser/items/categories/",
        "/_auth/shops/$shopId/_shopuser/items/substitutions/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/tabs": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser",
      "children": [
        "/_auth/shops/$shopId/_shopuser/tabs/$tabId"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/_layout/integrations": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/integrations.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/_layout/users": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/users.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/checkout/$itemId": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout/$itemId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/checkout",
      "children": [
        "/_auth/shops/$shopId/_shopuser/checkout/$itemId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/items/_index": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/_index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items",
      "children": [
        "/_auth/shops/$shopId/_shopuser/items/_index/$itemId",
        "/_auth/shops/$shopId/_shopuser/items/_index/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/tabs/$tabId": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs/$tabId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/tabs",
      "children": [
        "/_auth/shops/$shopId/_shopuser/tabs/$tabId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/_layout/": {
      "filePath": "_auth/shops/$shopId/_shopuser/_layout/index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/_layout"
    },
    "/_auth/shops/$shopId/_shopuser/items/_index/$itemId": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/_index.$itemId.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items/_index",
      "children": [
        "/_auth/shops/$shopId/_shopuser/items/_index/$itemId/"
      ]
    },
    "/_auth/shops/$shopId/_shopuser/checkout/$itemId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/checkout/$itemId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/checkout/$itemId"
    },
    "/_auth/shops/$shopId/_shopuser/items/_index/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/_index.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items/_index"
    },
    "/_auth/shops/$shopId/_shopuser/items/categories/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/categories.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items"
    },
    "/_auth/shops/$shopId/_shopuser/items/substitutions/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/substitutions.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items"
    },
    "/_auth/shops/$shopId/_shopuser/tabs/$tabId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/tabs/$tabId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/tabs/$tabId"
    },
    "/_auth/shops/$shopId/_shopuser/items/_index/$itemId/": {
      "filePath": "_auth/shops/$shopId/_shopuser/items/_index.$itemId.index.tsx",
      "parent": "/_auth/shops/$shopId/_shopuser/items/_index/$itemId"
    }
  }
}
ROUTE_MANIFEST_END */
