name: Backend Test CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache: true

      - name: Verify Dependencies
        run: go mod verify

      - name: Run Unit Tests
        run: go test -v -race ./...
